name: release-workflow-flowjo_10_9

on:
  workflow_dispatch:
  push:
    tags:
      - '*1.1.5*' # Push events to matching version. Releases from flowjo_10_9 branch = 1.1.5

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: TERCEN_VERSION
        run: echo "TERCEN_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Install artifact1
        run: mvn install:install-file -Dfile="third\FlowJo.jar" -DgroupId=com.flowjo -DartifactId=flowjo -Dversion=10.9.0 -Dpackaging=jar -DgeneratePom=true
      - name: Install artifact2
        run: mvn install:install-file -Dfile="third\fjlib-2.1.1-SNAPSHOT.jar" -DgroupId=com.flowjo -DartifactId=flowlib -Dversion=2.1.1 -Dpackaging=jar -DgeneratePom=true
      - name: Install artifact3
        run: mvn install:install-file -Dfile="third\fjengine-10.9.0-SNAPSHOT.jar" -DgroupId=com.flowjo -DartifactId=fjengine -Dversion=10.9.0 -Dpackaging=jar -DgeneratePom=true
      - name: Assemble
        run: mvn clean compile assembly:single
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get plugin version
        run: echo "PLUGIN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: move files
        run: | 
          mv "target/tercen-flowjo-plugin_v${{ env.PLUGIN_VERSION }}.jar" "./tercen-flowjo-plugin_v${{ env.PLUGIN_VERSION }}.jar"
      - uses: actions/upload-artifact@v2
        with:
          name: Tercen_v${{ env.PLUGIN_VERSION }}
          path: |
                tercen-flowjo-plugin_v${{ env.PLUGIN_VERSION }}.jar

