name: Publish package to GitHub Packages

on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: TERCEN_VERSION
        run: echo "TERCEN_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Install artifact1
        run: mvn install:install-file -Dfile="third\FlowJo.jar" -DgroupId=com.flowjo -DartifactId=flowjo -Dversion=10.8.0 -Dpackaging=jar -DgeneratePom=true
      - name: Install artifact2
        run: mvn install:install-file -Dfile="third\fjlib-2.4.0.jar" -DgroupId=com.flowjo -DartifactId=flowlib -Dversion=2.4.0 -Dpackaging=jar -DgeneratePom=true
      - name: Install artifact3
        run: mvn install:install-file -Dfile="third\fjengine-2.5.0.jar" -DgroupId=com.flowjo -DartifactId=fjengine -Dversion=2.5.0 -Dpackaging=jar -DgeneratePom=true
      - name: Assemble
        run: mvn clean compile assembly:single
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: tercen_flowjo_plugin
          path: target/tercen_plugin-${TERCEN_VERSION}-standalone.jar

