name: Publish package to GitHub Packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Install artifact1
        run: mvn install:install-file -Dfile="third\FlowJo.jar" -DgroupId=com.flowjo -DartifactId=flowjo -Dversion=10.8.0 -Dpackaging=jar -DgeneratePom=true
      - name: Install artifact2
        run: mvn install:install-file -Dfile="third\fjlib-2.4.0.jar" -DgroupId=com.flowjo -DartifactId=flowlib -Dversion=2.4.0 -Dpackaging=jar -DgeneratePom=true
      - name: Install artifact3
        run: mvn install:install-file -Dfile="third\fjengine-2.5.0.jar" -DgroupId=com.flowjo -DartifactId=fjengine -Dversion=2.5.0 -Dpackaging=jar -DgeneratePom=true
      - name: Pull tercen
        run: docker-compose pull
      - name: Start tercen
        run: docker-compose up -d
      - name: Build package
        run: mvn clean install -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop tercen
        run: docker-compose down
      - name: Get plugin version
        run: echo "PLUGIN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: Tercen_v${{ env.PLUGIN_VERSION }}
          path: |
                target/tercen-flowjo-plugin_v${{ env.PLUGIN_VERSION }}.jar
                doc/FlowJo Plugin Installation Instructions - PDF V1.0.4.pdf